### PR TITLE
(vmap_texture) a work-around for X11/AMD users

### PR DESCRIPTION
**Pull request by pioto1225**
Hi DisplayLink,

I am wondering if you would consider merging this for AMD/X11 users that suffer from slow screen updates when using DisplayLink devices. I came up with this solution a while ago already but I kept it on my branch (https://github.com/pioto1225/evdi/tree/amd_vmap_texture; more info available) because it is a hack-fix. This seems to be working quite well actually (I reckon AMD might have done some fixes in their drivers), and I have been getting some positive feedback over time:

- https://www.displaylink.org/forum/showthread.php?t=67580&page=2
- https://github.com/DisplayLink/evdi/issues/271#issuecomment-1064264962
- https://slimbook.es/en/forum/tag/station/question/7174-usb-c-no-trasmite-senal-hdmi-pro-x
- ....

This is not ideal solution, but I am not aware of anything better available at the moment(?). I reckon that the end users will benefit if they get this directly from DisplayLink instead of my branch which I could eventually retire.

Thanks.
Piotr

### CODE REVIEW

**Comment by displaylink-emajewsk** [comment]
I'll try it and see the results, then we'll consider the workaround.

**Comment by displaylink-emajewsk** [comment]
I'll try it and see the results, then we'll consider the workaround.

**Comment by stephenjfewer** [comment]
Hi all! Just wanted to say ... I bought a DisplayLink adapter a month and a bit ago. I had tried to use the display port ones, but my laptop doesn't support display port over usb-c or something.

When I got my display link adapter, I found that the performance was literally garbage, so just chucked it to the side and used only my laptop screen for the past bit.

_Luckily_ I just happened to come across the branch @pioto1225 mentions in this PR. I installed it a few minutes ago, and the performance is _lightyears_ better than what it was without it.

Much appreciated, I hope this, or something like this gets merged. I'll be running this branch nonetheless ... without it the adapter isn't usable. 

Atm, I'm running the following:

```bash
distro       : voidlinux
cpu          : AMD Ryzen 7 4800H with Radeon Graphics
linux kernel : 5.17.1 (patched/built with amd optimizations) 
xorg server  : 21.1.3_3
kde5         : 5.23.0_1

maybe some other stuff of use, from lspci?:
03:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 14 [Radeon RX 5500/5500M / Pro 5500M] (rev c1)
07:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Renoir (rev c6)

```

If anyone needs any testing, or if I can help in any way, please feel free to ping me, and I'll provide what I can! Thanks!

**Comment by pioto1225** [comment]
Hi.
I see the idea has now been taken ([commit](https://github.com/DisplayLink/evdi/commit/4f4687c2a0d0a552b4f3aba6ef3df421169b8191)). I will close my PR.
Piotr

**Comment by NikhilSaini38** [comment]
Received evdi-1.11.0 update in EVDI today and its working as it should out of the box. Thanks @pioto1225 for catching the issue and helping resolve problem that AMD users were facing by both providing amd-vmap-textures patch and notifying the contributors of EVDI and  @lspintzyk  and rest of collaborators for resolving it.

**Pull request closed without merging**
