### PR TITLE
Proper fixes for kernel >= 5.15

### PR DESCRIPTION
**Pull request by cdonatom**
A series of commits for fixing the module build on kernel >= 5.15.

### CODE REVIEW

**Comment by cdonatom** [comment]
Sorry for the several pull requests. This should be the final patch.

**Comment by francoism90** [comment]
@cdonatom @displaylink-emajewsk I've tested this on Arch Linux (`Linux desktop 5.15.5-zen1-1-zen #1 ZEN SMP PREEMPT Thu, 25 Nov 2021 22:09:35 +0000 x86_64 GNU/Linux`), it seems to compile and work fine. :)

**Comment by cdonatom** [comment]
Thanks for checking. Although, I am not sure about the new memory allocation I have introduced to replace compat_alloc_user_space(). It might leak memory since there's no kfree() associated. Researching the documentation, it is not clear to me what function should correctly replace compat_alloc_user_space().

**Comment by wspeirs** [comment]
> Thanks for checking. Although, I am not sure about the new memory allocation I have introduced to replace compat_alloc_user_space(). It might leak memory since there's no kfree() associated. Researching the documentation, it is not clear to me what function should correctly replace compat_alloc_user_space().

I went looking through commits to the kernel to see how others were handling removing `compat_alloc_user_space()`, and it _appears_ that memory is simply allocated on the stack. For example in [ALSA](https://github.com/torvalds/linux/commit/18d122c0287b#diff-ca0c75dd42699798637895ac609da5b6715fe8ddd5c76720358a08130e8e329b) and [USB](https://github.com/torvalds/linux/commit/c17536d0abde#diff-ff925b91f3e4dabd52372d014b4e2591563bfca489ce32302261522725e53bb5L2018).

Instances of `copy_in_user` are replaced with `copy_from_user` and `copy_to_user` where appropriate. Instances of `__put_user` or `put_user` are also no longer needed.

Disclaimer: not an expert here, just went spelunking to see how others were dealing with this because I use this module every day and would love to help :-)

**Comment by cdonatom** [comment]
This change will only affect Chrome(ium) OS users. If you know how to move forward, do not hesitate to fork my branch and push your changes for this.
I am now taking a look at night shift functionality, I think this is worth my time ;)

**Comment by iamarkadyt** [comment]
@cdonatom thanks for taking some time to develop a patch for this! :tada:

**Comment by displaylink-emajewsk** [comment]
This looks OK now. We can fix any potential issues before the December release. Thanks for the contribution. Cheers! :)

**Pull request merged**
