### PR TITLE
Linux 5.13 support

### PR DESCRIPTION
**Pull request by piso77**
See also upstream:
    
    commit 820c1707177c6fe96beed7f8cc842a683afbf890
    Author: Thomas Zimmermann <tzimmermann@suse.de>
    Date:   Mon Feb 22 15:17:56 2021 +0100
    
        drm/gem: Move drm_gem_fb_prepare_fb() to GEM atomic helpers

and

    commit 977697e20b3d758786b67edc33941e5c410ffe4d
    Author: Maxime Ripard <maxime@cerno.tech>
    Date:   Fri Feb 19 13:00:29 2021 +0100
    
        drm/atomic: Pass the full state to planes atomic disable and update

### CODE REVIEW

**Comment by lspintzyk** [comment]
This patch is failing build for kernel 5.4. To test that use
./ci/build_against_kernel 5.4 --ci --cached


Please invert KERNEL_VERSION conditionals statements as in the following example.
We use such pattern to keep it clean:

if KERNEL_VERSION(5, 13, 0) <= LINUX_VERSION_CODE
  // kernel 5.13, 5.14 and newer
if KERNEL_VERSION(5, 11, 0) <= LINUX_VERSION_CODE
 // kernel 5.11, 5.12
if KERNEL_VERSION(5, 4, 0) <= LINUX_VERSION_CODE
 // kernel 5.4  to 5.10
else
 // kernels older then 5.4
endif

**Comment by solbjorn** [comment]
For now, this PR build successfully ONLY on 5.13.0. Any versions lesser or higher (even 5.13.1) is broken.

I don't see any recent activity from the author. I could carry this PR, it only needs a few `#if` fixes.

**Comment by displaylink-emajewsk** [comment]
This PR was merged with additional fixes for other kernels. Already on `devel`.

**Comment by cherepanov** [comment]
Builds, but device is not detected, see no evdi events. Works fine with 5.12

**Comment by solbjorn** [comment]
@cherepanov, I've had no issues so far since migrating to the mainline 5.13 release in the same day as it has been released -- neither with the code from this PR nor now with the latest repo snapshot.

**Comment by cherepanov** [comment]
thx! complete module reinstall helped, for some reason it was failed to load

**Pull request closed without merging**
