### PR TITLE
Adjustments needed to support the latest kernel for RHEL/CentOS 8 and…

### PR DESCRIPTION
**Pull request by elguero**
… DKMS

- Add preprocessor conditionals - DRM in 8.3 been rebased to upstream
Linux kernel version 5.6

- Fixed DKMS support on RHEL/CentOS 8

### CODE REVIEW

**Comment by displaylink-dkurek** [comment]
Hi @elguero
Thanks for another PR :+1: 

Can we also add somehow a check for travis for those kernels?

The change for **module/Makefile** looks a bit suspicious. 
In root **Makefile** we are already adding `-D EL8` to `CFLAGS`.

Then in **module/Makefile**,
in **DKMS** section we are indeed ignoring it. Would it be fine to
add whole **CFLAGS** to **cflags-y** here?
for **Not DKMS** we add **CFLAGS** to **cflags-y**, isn't this working?

**Comment by elguero** [comment]
Good points.

I will see if we can adjust the Travis CI build to add a job for building against CentOS 8 in a docker container.

This new flag being defined, `EL8`, is only used when building under `modules`.  I almost removed it from the upper `Makefile` and moved it to the `modules\Makefile`.

What happens when using DKMS, the `modules\*` code is added to DKMS.  It is then built as a kernel module only using the `Makefile` that is under `modules`.  The `CFLAGS` is not set when it is built this way.

**Comment by displaylink-dkurek** [comment]
Yep, right. Then maybe it would be better to remove it from root Makefile and leave it only in module?
This makes sense as it's a kernel thing.
Could we define some variable in the 'global' scope in module/Makefile which would held the `-D EL8` (or nothing)
and reuse it in two places? I simply just want to remove the duplication of condition.

**Comment by elguero** [comment]
Let me know if this change looks good to you.  I think it addresses this properly and testing seems to show that it is working as expected.

Thanks for the good feedback.  I will see what I can do with the Travis-CI testing.

**Comment by displaylink-dkurek** [comment]
Thanks for the PR :+1: 
Now, hopefully in 2 days, we will have kernel 5.10 released :)

**Pull request merged**
