### PR TITLE
Fix return value of evdi_mode_valid

### PR DESCRIPTION
**Pull request by pedrib**
Since this commit:

commit 0993f1d0d8a1b516df4a059605af9979049d0187
Author: Damien Lespiau <damien.lespiau@intel.com>
Date:   Thu Nov 28 15:29:17 2013 +0000

    drm: Make the connector mode_valid() vfunc return a drm_mode_status enum
    
    To make it clear what exactly mode_valid() should return.
    
    Signed-off-by: Damien Lespiau <damien.lespiau@intel.com>
    Signed-off-by: Daniel Vetter <daniel.vetter@ffwll.ch>

upstream has returned enum drm_mode_status instead of int.  Functionally it shouldn't change anything as you're already returning stuff from that enum, and those enum values go back to at least 2008, so it should be a perfectly compatible change to make.  

This patch comes from the grsecurity project, and it will fix compatibility with RAP and other fine-grained kernel CFI methods.

### CODE REVIEW

**Comment by pedrib** [comment]
Failed to pass the Travis check, but I don't think it has to do with my commit?

**Comment by tartansandal** [comment]
One of the travis errors is from the code style checker and should be easy to fix.

The other is just the build against the master kernel, which looks a lot like the issue https://github.com/DisplayLink/evdi/issues/99

**Comment by dawikur** [comment]
@pedrib,
Can you rebase? This should trigger travis re-run, which hopefully will now pass . :)

**Comment by pedrib** [comment]
@dawikur done! I don't really understand the style check complaint, what is it about?

**Comment by dawikur** [comment]
Take a look at c495c74ada5a89c186b10ff7945d6e69701595c2.
The first version uses the function name in message, which is kinda duplicating it. If you would change the function name, you have to change it in more than one place.

**Comment by pedrib** [comment]
I see... thanks for the explanation. Looks like it's ready to go?

**Pull request merged**
