### PR TITLE
include builds for linux 4.15 and 4.16

### PR DESCRIPTION
**Pull request by mrTsjolder**
practically a duplicate of #121, which seems to be lost

### CODE REVIEW

**Comment by dawikur** [comment]
Hi, good stuff :)

Is '-Wno-error=missing-field-initializers' needed? Maybe we can simply add missing initializers?

Can you unify comments style?
Sometimes it is
```
//
//
```
or
```
/* */
//
```
```
/*
 *
```
Weird ;)

And the last one, according to 
https://github.com/DisplayLink/evdi/blob/devel/library/LICENSE
library is indeed on LGPL 2.1
but this
https://github.com/DisplayLink/evdi/blob/devel/module/LICENSE
says module is on GPL 2
but you have added LGPL to both :)

**Comment by mrTsjolder** [comment]
I copied this workaround from #121. The comment states that this is due to uninitialised struct fields in linux, so I am not sure whether it makes sense to initialise them. Maybe @jtdoepke might be able to provide some more details to this.
 
I'll see what I can do on the unification.
The last one is a copy-paste error, sorry.

**Comment by mrTsjolder** [comment]
@dawikur It turns out that unified comment style is not an option:

 * `.c` files are expected to start with the exact string `// SPDX-License-Identifier: `
 * `.h` files are expected to start with the exact string `/* SPDX-License-Identifier: `

Unless you want to have all multi-line comments to start with `//`, unified comment style seems not to be an option (yet).

PS: I don't like this either (at all)

**Comment by jtdoepke** [comment]
IIRC, the uninitialized fields came from the Linux kernel, so nothing to do about it in this repo other than suppress the warning.

**Comment by laurenblackfox** [comment]
Really hate to be the only one bugging you guys about this, but do we have an ETA on a merge?

**Comment by ACiDGRiM** [comment]
Come on guys, please support your product. I bought display-link specifically for Linux support.

**Comment by displaylink-dkurek** [comment]
Sorry it took so long. We have finally again 'green' build :)

**Comment by Giszmo** [comment]
I've been looking around but I can't see how to use the latest version. I installed running `displaylink-driver-4.2.29.run` and see nothing new running `xrandr`, so I assume this patch for my kernel is not yet in displaylink driver 4.2.29. How do I proceed to make use of my new StarTech toy?

**Comment by mrTsjolder** [comment]
You probably want to start [a new issue](https://github.com/DisplayLink/evdi/issues/new) if you didn't find what you were looking for in the [existing issues](https://github.com/DisplayLink/evdi/issues) like e.g. #133. This thread is most likely not related to your problem.

**Pull request merged**
