### PR TITLE
Fix compilation against Linux 4.19.

### LINKED ISSUE #139: Issue with Linux mint 18.3 kernal 4.19
Getting following error in latest Mint 18.3  4.19 kernal

```
DKMS make.log for evdi-4.2.29 for kernel 4.19.0-041900rc5-generic (x86_64)
Wed Sep 26 17:09:45 CEST 2018
make KBUILD_VERBOSE=1 SUBDIRS=/var/lib/dkms/evdi/4.2.29/build SRCROOT=/var/lib/dkms/evdi/4.2.29/build CONFIG_MODULE_SIG= -C /lib/modules/4.19.0-041900rc5-generic/build modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.0-041900rc5-generic'
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (		\
echo >&2;							\
echo >&2 "  ERROR: Kernel configuration is invalid.";		\
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";	\
echo >&2 ;							\
/bin/false)
mkdir -p /var/lib/dkms/evdi/4.2.29/build/.tmp_versions ; rm -f /var/lib/dkms/evdi/4.2.29/build/.tmp_versions/*
make -f ./scripts/Makefile.build obj=/var/lib/dkms/evdi/4.2.29/build
(cat /dev/null;   echo kernel//var/lib/dkms/evdi/4.2.29/build/evdi.ko;) > /var/lib/dkms/evdi/4.2.29/build/modules.order
  gcc -Wp,-MD,/var/lib/dkms/evdi/4.2.29/build/.evdi_drv.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/5/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -DCC_HAVE_ASM_GOTO -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -DRETPOLINE -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fstack-protector-strong -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Iinclude/drm  -DMODULE  -DKBUILD_BASENAME='"evdi_drv"' -DKBUILD_MODNAME='"evdi"' -c -o /var/lib/dkms/evdi/4.2.29/build/evdi_drv.o /var/lib/dkms/evdi/4.2.29/build/evdi_drv.c
   ./tools/objtool/objtool check  --module --retpoline "/var/lib/dkms/evdi/4.2.29/build/evdi_drv.o";
  gcc -Wp,-MD,/var/lib/dkms/evdi/4.2.29/build/.evdi_modeset.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/5/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -DCC_HAVE_ASM_GOTO -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -DRETPOLINE -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fstack-protector-strong -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Iinclude/drm  -DMODULE  -DKBUILD_BASENAME='"evdi_modeset"' -DKBUILD_MODNAME='"evdi"' -c -o /var/lib/dkms/evdi/4.2.29/build/evdi_modeset.o /var/lib/dkms/evdi/4.2.29/build/evdi_modeset.c
   ./tools/objtool/objtool check  --module --retpoline "/var/lib/dkms/evdi/4.2.29/build/evdi_modeset.o";
  gcc -Wp,-MD,/var/lib/dkms/evdi/4.2.29/build/.evdi_connector.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/5/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -DCC_HAVE_ASM_GOTO -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -DRETPOLINE -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fstack-protector-strong -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Iinclude/drm  -DMODULE  -DKBUILD_BASENAME='"evdi_connector"' -DKBUILD_MODNAME='"evdi"' -c -o /var/lib/dkms/evdi/4.2.29/build/evdi_connector.o /var/lib/dkms/evdi/4.2.29/build/evdi_connector.c
/var/lib/dkms/evdi/4.2.29/build/evdi_connector.c: In function ‘evdi_get_modes’:
/var/lib/dkms/evdi/4.2.29/build/evdi_connector.c:34:3: error: implicit declaration of function ‘drm_mode_connector_update_edid_property’ [-Werror=implicit-function-declaration]
   drm_mode_connector_update_edid_property(connector, NULL);
   ^
/var/lib/dkms/evdi/4.2.29/build/evdi_connector.c: In function ‘evdi_connector_init’:
/var/lib/dkms/evdi/4.2.29/build/evdi_connector.c:146:2: error: implicit declaration of function ‘drm_mode_connector_attach_encoder’ [-Werror=implicit-function-declaration]
  drm_mode_connector_attach_encoder(connector, encoder);
  ^
cc1: some warnings being treated as errors
scripts/Makefile.build:305: recipe for target '/var/lib/dkms/evdi/4.2.29/build/evdi_connector.o' failed
make[2]: *** [/var/lib/dkms/evdi/4.2.29/build/evdi_connector.o] Error 1
Makefile:1515: recipe for target '_module_/var/lib/dkms/evdi/4.2.29/build' failed
make[1]: *** [_module_/var/lib/dkms/evdi/4.2.29/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.0-041900rc5-generic'
Makefile:22: recipe for target 'all' failed
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by kugel-**
Fixes #139

### CODE REVIEW

**Comment by cristim** [comment]
TravisCI warns about a few style issues, please fix these:

image

**Comment by cristim** [comment]
I just tested this patch on the latest 4.19 RC and I confirm it works like a charm!

The procedure is a bit complicated, so it should be integrated properly in the driver binaries after merging this PR.

**Comment by kugel-** [comment]
`Comparisons should place the constant on the right side of the test` ??? What a misguided check. In this case two constants are compared. Takes ma while to grasp the test `KERNEL_VERSION(4, 19, 0) > LINUX_VERSION_CODE`

**Comment by kugel-** [comment]
Obsoleted by 1.5.1 (c7e80bc32c2ef96464613fbbda15fd930bf6fb41)

**Pull request closed without merging**
