### PR TITLE
Adjust to kernel 5.9

### PR DESCRIPTION
**Pull request by abucodonosor**
Please note I do not have any HW to test these changes.

### CODE REVIEW

**Comment by sickcodes** [comment]
devel branch doesn't work on my hardware, but your fix also fixes the 1.7.0 tag, which is what need here https://aur.archlinux.org/packages/displaylink/

**Comment by abucodonosor** [comment]
@sickcodes 

is that a known issue on the devel branch & your HW?

**Comment by sickcodes** [comment]
Not just me, everyone on Arch Linux is using EVDI 1.7.0, apparently we're waiting for DisplayLink?

https://github.com/DisplayLink/evdi/issues/216#issuecomment-673740653

https://aur.archlinux.org/packages/displaylink/

EVDI for displaylink in the AUR is set to 1.7.0 (which is the master branch here for anyone reading this) so that's why I pushed your changes there too, which built perfectly.

**Comment by bnavigator** [comment]
> Not just me, everyone on Arch Linux is using EVDI 1.7.0, apparently we're waiting for DisplayLink?
> 
> [#216 (comment)](https://github.com/DisplayLink/evdi/issues/216#issuecomment-673740653)

https://github.com/DisplayLink/evdi/issues/225#issuecomment-708234977 too

**Comment by abucodonosor** [comment]
> > Not just me, everyone on Arch Linux is using EVDI 1.7.0, apparently we're waiting for DisplayLink?
> > [#216 (comment)](https://github.com/DisplayLink/evdi/issues/216#issuecomment-673740653)
> 
> [#225 (comment)](https://github.com/DisplayLink/evdi/issues/225#issuecomment-708234977) too

Oh ok, I thought, there may be a code problem in the devels branch causing the HW to not work.

**Comment by dummys** [comment]
Hi guys, 
am I the only one to not be able to restart displaymanager whitout crashing the driver ?

when I connect displaylink, I can switch to the screen, whitout problem, but when restarting lightdm, no more screen, and huge crash in the journalctl. I tried connecting usb before boot, same problem. I tried switching back to the laptop screen before restarting lightdm, same problem. My kernel version is: 5.8.14-arch1-1 OS: Arch linux

**Comment by bnavigator** [comment]
> My kernel version is: 5.8.14-arch1-1 OS: Arch linux

Please open a new issue. Not posting in the kernel 5.9 threads.

**Comment by joren485** [comment]
@displaylink-dkurek Is there an ETA on getting this PR merged and released?

[Linux 5.9](https://www.archlinux.org/packages/core/x86_64/linux/) was just [released into the Core repo of Arch Linux](https://github.com/archlinux/svntogit-packages/commits/packages/linux/trunk), which means all Arch Linux users will need this patch.

I can confirm that this patch works on my 5.9 system (I use the [patched evdi AUR package](https://aur.archlinux.org/packages/evdi-1.7/) by @bnavigator).

**Comment by sickcodes** [comment]
> > I can confirm that this patch works on my 5.9 system (I use the [patched evdi AUR package](https://aur.archlinux.org/packages/evdi-1.7/) by @bnavigator).

Yup but the patch comes from https://github.com/DisplayLink/evdi/pull/228 😂

**Comment by sickcodes** [comment]
Greetings @displaylink-dkurek when do you think this will this be getting merged? Can we help? @abucodonosor is a professor!

**Comment by displaylink-dkurek** [comment]
Sorry it took so long :)

**Comment by sickcodes** [comment]
> Sorry it took so long :) 

Fantastic! Will you backport it for 1.7 or 1.7.1? Shall I close #228?

**Comment by joren485** [comment]
@displaylink-dkurek The [build just failed](https://travis-ci.org/github/DisplayLink/evdi/jobs/737678724).

**Comment by displaylink-dkurek** [comment]
Thanks for pinging me.
Compilations with all supported kernels were fine.
It's style check which failed. Will take a look at it (seems the script changed).

**Comment by displaylink-dkurek** [comment]
Found the thread:
https://lkml.org/lkml/2020/10/18/118

Seems there is missing commit on github/torvalds/linux. We still have 4 days
of the merge window. Hope the missing things will be merged by the end of it.
Let's wait maybe a day or two and in the meantime I will think about making
the stylecheck less sensitive for problems like this in the future.

**Comment by joren485** [comment]
My shot at a fix: #230

**Pull request merged**
